#!/usr/bin/env bash

PATH="@citrix@/bin:$PATH"
NAME=$(basename "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")

set -u

XHOME=$(mktemp --directory)
create_home() {
	mkdir --parent "$XHOME"
	mkdir --parent "$XHOME/.ICAClient"
	if [ -e "$HOME"/.ICAClient/wfclient.ini ]; then
		cp --verbose \
			"$HOME"/.ICAClient/wfclient.ini \
			"$XHOME"/.ICAClient/wfclient.ini
	fi
	touch "$XHOME/.ICAClient/.eula_accepted"
}

create_home
ORIG="${1}"
if [ ! -f "$ORIG" ]; then
	echo >/dev/stderr "not found: $ORIG"
	exit 8
fi
COPY_NAME="$$.ica"
COPY="$XHOME/$COPY_NAME"
cp --verbose "$ORIG" "$COPY"

{
	while :; do
		xdotool search --class Wfica \
			key --window %@ XF86AudioMute \
			key --window %@ XF86AudioMute
		sleep "$(($RANDOM % 60 + 120))"
	done
} &

exec firejail \
	--name="$NAME" \
	--netlock \
	--env=LC_ALL=en_US.UTF-8 \
	--env=TZ=America/New_York \
	--caps.drop=all \
	--hostname="localhost" \
	--private="$XHOME" \
	--private-dev \
	--private-etc \
	--nosound \
	--novideo \
	--cpu=0,1 \
	--machine-id \
	wfica "$COPY"
