#!/usr/bin/env bash

PATH="$PATH:@citrix@/bin"
NAME=$(basename "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")

set -u

XHOME=$(mktemp --directory)
create_home() {
	mkdir --parent "$XHOME"
	mkdir --parent "$XHOME/.ICAClient"
	if [ -e "$HOME"/.ICAClient/wfclient.ini ]; then
		cp --verbose \
			"$HOME"/.ICAClient/wfclient.ini \
			"$XHOME"/.ICAClient/wfclient.ini
	fi
	touch "$XHOME/.ICAClient/.eula_accepted"
}

create_home

ORIG="${1}"
COPY="$XHOME/$(basename $ORIG)"
if [ ! -f "$ORIG" ]; then
	echo >/dev/stderr "not found: $ORIG"
	exit 8
fi
cp --verbose "$ORIG" "$COPY"

LC_ALL=en_US.UTF-8
TZ=America/New_York
export TZ LC_ALL

{
	while :; do
		xdotool search --class Wfica \
			key --window %@ Super \
			key --window %@ Escape
		sleep "$(($RANDOM % 60 + 120))"
	done
} &

exec firejail \
	--name="$NAME" \
	--private="$XHOME" \
	--nosound \
	--novideo \
	--private-dev \
	--cpu=0,1 \
	--machine-id \
	wfica "$COPY"
